# Generated by Django 3.2.7 on 2021-10-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
