# Generated by Django 3.2.7 on 2021-10-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
